name: Hämta Rollspelstråd

on:
  workflow_dispatch:
    inputs:
      thread_url:
        description: 'URL till tråden'
        required: true

        jobs:
          download-thread:
            runs-on: ubuntu-latest
            steps:
              - name: Klona repo
                uses: actions/checkout@v3

              - name: Installera beroenden
                run: |
                  python -m pip install --upgrade pip
                  pip install beautifulsoup4 requests

              - name: Hämta tråd
                run: |
                  python fetch_thread.py "${{ github.event.inputs.thread_url }}"

              - name: Spara ändringar i repo
                run: |
                  git config user.name "GitHub Action"
                  git config user.email "actions@github.com"
                  git add data/
                  git commit -m "Laddade ner tråd ${{ github.event.inputs.thread_url }}" || echo "Inga ändringar"
                  git push
