name: Automatisk hämtning av tråd

on:
  schedule:
    - cron: '*/30 * * * *'  # var 30:e minut
  workflow_dispatch:     # valfritt: för manuell körning

jobs:
  download-thread:
    runs-on: ubuntu-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera beroenden
        run: |
          pip install requests beautifulsoup4

      - name: Hämta tråd
        env:
          THREAD_URL: https://www.rollspel.nu/threads/bh-ii-r2.85331
        run: |
          python fetch_thread.py

      - name: Committa ändringar
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Automatiskt uppdaterad tråd bh-ii-r2.85331" || echo "Inga ändringar"
          git push
